### ISSUE TITLE
Problem with the module manifest

### ISSUE THREAD

**Issue by yznerf** [imseandavis/PSTerminalServices#2]
I am not sure, if this module is still maintained, but I like it very much, so I wanted to report an issue.

There is an error in the manifesto, in the "Module Version". 
```
# Version number of this module.
ModuleVersion = '1.0'
```
Because of this, after installing the module the cmdlets are not available. 

An Import-Module command gives:
```
PS C:\WINDOWS\system32> Import-Module PSTerminalServices
Import-Module : Das angegebene Modul "PSTerminalServices" wurde nicht geladen, da in keinem Modulverzeichnis eine
gültige Moduldatei gefunden wurde.
In Zeile:1 Zeichen:1
+ Import-Module PSTerminalServices
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (PSTerminalServices:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
```

After changing the mentionend line in the manifest to: 
```
# Version number of this module.
ModuleVersion = '1.0.0'
```
everything works correctly. This might have to to with the name of the folder in which the module resides. It is the very same '1.0.0'.

I hope that you get arround to fix this little inconsistency, so that more people will use this awesome module! 

System Details:

Operating System: Win 11 22H2
Microsoft Windows 11 Enterprise
10.0.22631 Build 22631

Powershell version:
```
PS C:\WINDOWS\system32> $psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.22621.2506
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2506
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by imseandavis** [comment]
I will get this updated shortly. Thanks for the call out.

**Comment by imseandavis** [comment]
Updated. Please verify working and I'll close.

**Comment by yznerf** [comment]
Works like a charm! Thank you!

**Comment by imseandavis** [comment]
Verified
